chef/gatherlogs-reporter

chef-server/controls/issues.rb

This looks for messages in the logs related to depsolver being killed

adding check for depsolver timeout issues

---

chef-server/controls/push_jobs_issues.rb
common/controls/basic.rb
glresources/libraries/log_analysis.rb

Add push jobs hostname error check

---

chef-server/controls/issues.rb

This will look in the opscode_erchef logs to find connection error
messages.
Resolves #7

Adds check for rabbitmq connection errors

---

automate/controls/basic.rb
glresources/libraries/disk_usage.rb

Need to normalize file sizes to MB before comparison

---

chef-server/controls/issues.rb
glresources/libraries/common_logs.rb
glresources/libraries/installed_packages.rb

this will check for bad_actor messages in erchef logs

---

chef-server/controls/issues.rb
chef-server/inspec.yml
glresources/inspec.yml
glresources/libraries/common_logs.rb

add a check for solr4 reporting memory allocation errors

---

automate2/controls/basic.rb
automate2/inspec.yml

Add notification post error check

---

automate2/controls/basic.rb
automate2/inspec.yml
glresources/inspec.yml
glresources/libraries/log_analysis.rb

Add ElasticSearch garbage collection log checks

---

glresources/inspec.yml
glresources/libraries/installed_packages.rb
glresources/libraries/platform_version.rb

Add platform detection for centos

---

automate/inspec.yml
automate2/controls/basic.rb
automate2/controls/issues.rb

This also moves the other heap based error check into the issues.rb
control file

Adding check for oom errors from ElasticSearch

---

chef-backend/README.md
chef-backend/controls/basic.rb
chef-backend/inspec.yml
glresources/inspec.yml
glresources/libraries/installed_packages.rb

adding the start of support for chef-backend

---

common/controls/basic.rb
common/inspec.yml

Update oom killer desc to use summary helper method

---

automate2/controls/basic.rb
automate2/inspec.yml
common/controls/basic.rb
common/inspec.yml
glresources/inspec.yml
glresources/libraries/log_analysis.rb

This should strip thouse out to help make the output a bit more compact

Some methods were returning extra newlines

---

chef-backend/controls/basic.rb
chef-backend/inspec.yml
glresources/inspec.yml
glresources/libraries/service_status.rb

Add checks for chef-backend services

---

automate/controls/issues.rb
automate/inspec.yml
automate2/controls/basic.rb
automate2/controls/issues.rb
automate2/inspec.yml
bin/pretty.rb
chef-backend/controls/basic.rb
chef-backend/inspec.yml
chef-server/controls/issues.rb
chef-server/controls/push_jobs_issues.rb
chef-server/controls/reporting_issues.rb
common/controls/basic.rb
common/inspec.yml

This way you can specify links to knowledge base links and summary info
to show as part of the output

This adds support for specifying tags

---

bin/pretty.rb

Also adds some method documentation

Clean up methods used to format the inspec output

---

bin/check_logs
bin/pretty.rb

Refactor reporter code into a class

---

common/controls/basic.rb

Update contrack control to use tags

---

bin/pretty.rb

Moving constants into reporter class

---

lib/gatherlogs.rb
lib/gatherlogs/version.rb
profiles/chef-server/controls/drbd.rb
profiles/chef-server/inspec.yml

Now detects if chef-server is configured with drbd

---

Gemfile.lock
bin/server
gatherlogs.gemspec
habitat/hooks/run
habitat/plan.sh

Adding a simple sinatra app for executing job remotely

---

profiles/automate2/controls/issues.rb
profiles/automate2/inspec.yml

1. Butterfly dat file corruption check
2. Check for issue with too many workers in the LB

Add a couple of profiles for A2

---

lib/gatherlogs/cli.rb
lib/gatherlogs/reporter.rb
profiles/automate2/controls/basic.rb
profiles/automate2/inspec.yml
profiles/chef-server/controls/addons.rb
profiles/chef-server/controls/basic.rb
profiles/chef-server/controls/ha.rb
profiles/chef-server/controls/push_jobs_issues.rb
profiles/chef-server/inspec.yml
profiles/common/controls/basic.rb
profiles/common/inspec.yml
profiles/glresources/inspec.yml
profiles/glresources/libraries/memory.rb

Revamp system info to use a hash

---

lib/gatherlogs/cli.rb
profiles/automate/controls/basic.rb
profiles/automate/inspec.yml
profiles/chef-backend/controls/basic.rb
profiles/chef-backend/inspec.yml
profiles/chef-server/controls/basic.rb
profiles/chef-server/controls/push_jobs_issues.rb
profiles/chef-server/inspec.yml
profiles/common/controls/basic.rb
profiles/common/inspec.yml
profiles/glresources/inspec.yml
profiles/glresources/libraries/cpu_info.rb

Add checks for cpu requirements

---

lib/gatherlogs/cli.rb
lib/gatherlogs/control_report.rb
lib/gatherlogs/output.rb
lib/gatherlogs/reporter.rb
spec/gatherlogs/control_report_spec.rb

Inspec appears to include them in the json results twice, once with an
empty result set

Turns out that included controls were showing up twice

---

lib/gatherlogs/cli.rb
spec/gatherlogs/cli_spec.rb

disable lock file due to hab perm error

---

profiles/chef-server/controls/issues.rb
profiles/chef-server/inspec.yml

add check for stale oc_id service and solr4 heap

---

lib/gatherlogs/product.rb
profiles/chef-server/controls/addons.rb
profiles/chef-server/controls/basic.rb
profiles/chef-server/inspec.yml

Also includes the license count of set

This adds checks for older chef-server and sync products

---

profiles/chef-server/controls/basic.rb

Fixes issue with gettting license count for CS

---

lib/gatherlogs/output.rb
profiles/common/controls/basic.rb
profiles/common/inspec.yml
profiles/glresources/inspec.yml
profiles/glresources/libraries/log_analysis.rb
spec/gatherlogs/output_spec.rb

Also fixes some formatting issues

This adds some checks for XFS disk errors

---

profiles/glresources/libraries/cpu_info.rb

add support for power8 cpu info

---

profiles/automate/controls/basic.rb
profiles/automate/inspec.yml
profiles/automate2/controls/basic.rb
profiles/automate2/inspec.yml
profiles/glresources/inspec.yml
profiles/glresources/libraries/service_status.rb

This also adds a check for the service list output to make sure it
exists

Clean up service checks for A1 and A2

---

profiles/common/controls/basic.rb
profiles/common/inspec.yml

Add link to the new A2 scaling docs

---

profiles/automate2/controls/elasticsearch.rb
profiles/automate2/controls/issues.rb
profiles/automate2/inspec.yml

This will check for Postgresql complaining about too many connections
and ElasticSearch errors about immense term values

Add 2 checks for PG and ES issues

---

gatherlogs.gemspec
profiles/chef-server/controls/erchef.rb
profiles/chef-server/inspec.yml

Adds some info about things to check for the bookshelf 5000ms timeout

Update bookshelf error

---

profiles/chef-server/controls/basic.rb
profiles/chef-server/controls/ha.rb
profiles/chef-server/inspec.yml

Also adds a quick check for ldap configs

Clean up sysinfo output

---

.rubocop.yml
profiles/automate2/controls/issues.rb
profiles/automate2/inspec.yml
profiles/chef-backend/controls/issues.rb
profiles/chef-backend/inspec.yml
profiles/chef-server/controls/erchef.rb
profiles/chef-server/inspec.yml
profiles/glresources/inspec.yml
profiles/glresources/libraries/log_analysis.rb

Adds several checks and a small output change for quality of life

New support checks

---

profiles/glresources/inspec.yml
profiles/glresources/libraries/platform_version.rb

Also switch platform file to prefer the os-release when available

Adding platform version id to output

---

profiles/automate2/controls/issues.rb

Adds check for a large number of open ports for A2

---

profiles/automate2/controls/elasticsearch.rb
profiles/automate2/controls/issues.rb
profiles/glresources/libraries/log_analysis.rb
spec/gatherlogs/output_spec.rb

ElasticSearch Insufficent memory java error

---

profiles/automate2/controls/issues.rb

Adding check for permission error generating certs

---

profiles/glresources/libraries/log_analysis.rb

This limits the log line length to 2000 chars

---

profiles/chef-backend/controls/basic.rb

Backend clock sync

---

profiles/common/controls/antivirus.rb

Add av entry

---

profiles/chef-server/controls/issues.rb
profiles/chef-server/inspec.yml

This adds a couple of checks for keygen related issues

---

profiles/automate2/controls/elasticsearch.rb

Add check for ES primary shard errors

---

profiles/automate2/controls/elasticsearch.rb
profiles/automate2/inspec.yml

Add a check for readonly ES indicies

---

.travis.yml
profiles/automate2/controls/issues.rb
profiles/automate2/inspec.yml

Check for AudienceRestriction assertion errors in SAML responses

---

CHANGELOG.md

Adding CHANGELOG.md to repo

---

profiles/automate/controls/basic.rb

Titles, descriptions, impacts, formatting for each control
Signed-off-by: Thomas Gordon <nrgetik@users.noreply.github.com>

First pass to clean up basic checks for Automate 1

---

.expeditor/config.yml
.expeditor/verify.pipeline.yml
CHANGELOG.md
README.md

Adding expeditor configs
TODO:

Adding start of expeditor config

---

.expeditor/verify.pipeline.yml
profiles/automate2/controls/basic.rb
scripts/bk_container_prep.sh

Add a check to make sure the system has the required number of CPU cores
Closes #109

Adding check for required cpu counts

---

Gemfile.lock
README.md
gatherlogs_reporter.gemspec
lib/gatherlogs/cli.rb
profiles/automate/README.md
profiles/automate/controls/issues.rb
profiles/automate/inspec.yml
profiles/automate2/README.md
profiles/automate2/inspec.yml
profiles/chef-backend/README.md
profiles/chef-backend/inspec.yml
profiles/chef-server/README.md
profiles/chef-server/inspec.yml
profiles/common/README.md
profiles/common/inspec.yml

Documentation and various text fixes

---

.bldr.toml
.expeditor/build.habitat.yml

Attempting to determine why buildkite is failing

---

.expeditor/config.yml

Adding configs for expeditor promotions

Add build promotions

---

CHANGELOG.md

Remove test entries from changelog

---

Gemfile.lock
bin/gatherlogs_report
bin/gatherlogs_report.rb
lib/gatherlogs/cli.rb
lib/gatherlogs/version.rb
service/.rubocop.yml
spec/gatherlogs/version_spec.rb

It looks like there is an issue with the way bundler is pulling in deps when using chef-workstation.  This is an attempt at forcing the command to run in the environment I want instead of with chef-workstations ruby environment.

Deal with bundler

---

Gemfile.lock
README.md
bin/gatherlog
bin/gatherlogs_report
bin/gl-commands
bin/gl-help
bin/gl-init
bin/gl-profiles
bin/gl-report
bin/gl-sh-shell
bin/gl-update
bin/gl-version
completions/gatherlogs_report.zsh
lib/gatherlogs.rb
lib/gatherlogs/cli.rb
lib/gatherlogs/profiles.rb
lib/gatherlogs/version.rb
service/Gemfile.lock
service/Rakefile
service/lib/grese/webhook_server.rb
service/spec/grese/webhook_server_spec.rb
spec/gatherlogs/cli_spec.rb
spec/gatherlogs/profiles_spec.rb
spec/gatherlogs/version_spec.rb

Splitting out functionality for the CLI into separate scripts. This will help to reduce the size of the CLI class.

Upgrade cli scripts

---

bin/gl-version

Add help for version command

---

bin/gl-update
completions/gatherlogs_report.zsh

Add todo for checking install type for update command and add `-p` for autocomplete detection

Misc updates

---

Gemfile.lock
bin/console
bin/gl-profiles
service/Gemfile.lock
service/spec/spec_helper.rb
spec/spec_helper.rb

Removing all references for bundler/setup

---

README.md

Quick update to readme for the license

Adding license and author info to readme
