automate/controls/issues.rb
glresources/libraries/installed_packages.rb

It doesn't appear that `automate-ctl gather-logs` includes a `installed-packages.txt` file so we need to check for the version-manifest.txt to attempt to determine the version.

Handle checking automate version

---

automate2/controls/basic.rb
glresources/libraries/log_analysis.rb

Currently this is adding support for preflight checks from Automate v2

Adding checks preflight failures for A2

---

automate2/controls/issues.rb
bin/check_logs

This adds a check when the `hab sub` upgrade fails

Add automate2 issue controls

---

automate2/controls/basic.rb
automate2/controls/issues.rb
automate2/inspec.yml
glresources/inspec.yml
glresources/libraries/service_status.rb

Adds a new summary method for the service status and also updates a2 to
look for the health check output for services

Fix up service checks for a2 to look at health

---

lib/gatherlogs/cli.rb

If the user wasn't actually fetching a remote file this would generate
and error trying to clean up a non-existent cache directory

This fixes error when trying to cleanup tmp location

---

BUILD.md
bin/server
lib/gatherlogs/webhook_server.rb

~in the same comment and~ also updates ugly output when there are no
failures returned by the inspec profiles
Turns out the fix is in the zendesk trigger and not here for multiple attachments

Fix output if no failures from inspec

---

lib/gatherlogs/product.rb

This is needed incase the gather-logs command is run in local mode.
This can happen if the deployment service is not running.
Also this reverses the key/values for the product detection as the files are the unique bit and not the product name

Adding a secondary check for automate2

---

.rubocop.yml
profiles/glresources/libraries/log_analysis.rb

Grep that comes with MacOS works fine using extended regexp but in order
for some of the matchers to work right the hab/linux version needs to
use perl.

Turns out that on linux we need to use perl regexp

---

profiles/automate/controls/basic.rb
profiles/automate2/inspec.yml
profiles/glresources/inspec.yml
profiles/glresources/libraries/sysctl.rb

I recently broke this when I renamed the class to sysctl from sysctl_a

Fix the sysctl custom resource for inspec

---

lib/gatherlogs/control_report.rb

This was happening because we were skipping any controls that had no
results.  This moves the pull of system info to before the skip

Fix uptime and cpu info not showing up

---

.rubocop.yml
profiles/glresources/inspec.yml
profiles/glresources/libraries/log_analysis.rb

This defaults to a really high value (100000 lines) that should only impact journalctl logs from A2.  Gatherlogs from other products already limits files to 10K lines.

Use tail to limit number of lines we search for in log files

---

profiles/chef-server/controls/issues.rb

Some older versions of Berkself do not properly handle setting the API
version for cookbook uploads and will attempt to send an older manifest
format with the new api version.

Adds a check for segement api version error

---

profiles/automate/controls/workflow.rb
profiles/automate/inspec.yml

It's possible that the process that manages status of workflow's runners
was terminated.  This finds when that happens

Find when workflow runner terminated

---

profiles/automate2/controls/issues.rb
profiles/common/controls/basic.rb
profiles/glresources/libraries/common_logs.rb

Supports chef-server, automate and a2
This replaces #92 with a more generic check.

This migrates the A2 port usage check to be a common check

---

lib/gatherlogs/cli.rb
lib/gatherlogs/control_report.rb
lib/gatherlogs/reporter.rb
profiles/automate/controls/issues.rb
profiles/automate/inspec.yml
profiles/automate2/controls/basic.rb
profiles/automate2/controls/elasticsearch.rb
profiles/automate2/controls/issues.rb
profiles/automate2/inspec.yml
profiles/chef-backend/controls/basic.rb
profiles/chef-backend/controls/issues.rb
profiles/chef-backend/inspec.yml
profiles/chef-server/controls/erchef.rb
profiles/chef-server/controls/issues.rb
profiles/chef-server/inspec.yml
spec/gatherlogs/cli_spec.rb
spec/gatherlogs/control_report_spec.rb
spec/gatherlogs/reporter_spec.rb

As a support engineer I would like to be able to have the gatherlogs reporter automatically reply to tickets when `critical` issues are found in the log bundle.
---
This adds a filter for results to only be shown when above given impact value.
To use this we will need to specify an `impact` value in the profile controls
From: https://www.inspec.io/docs/reference/dsl_inspec/
```
impact is a string, or numeric that measures the importance of the compliance results. 
Valid strings for impact are none, low, medium, high, and critical. 
The values are based off CVSS 3.0. A numeric value must be between 0.0 and 1.0. 
The value ranges are:
0.0 to <0.01 these are controls with no impact, they only provide information
0.01 to <0.4 these are controls with low impact
0.4 to <0.7 these are controls …
```

Add impact filter

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/membership.md
CODE_OF_CONDUCT.md

Adds code of conduct and GH issue templates from https://github.com/chef/oss_project_boilerplate

Adding oss code of conduct and GH templates

---

.expeditor/config.yml
Gemfile.lock
service/Gemfile.lock
service/gatherlogs_service.gemspec

When the hab pkg is being built version files from the root are copied to the root of the service build directory.  This will attempt to figure out the correct version file to load for the gemspec.

Fix version handling when building hab pkgs

---

.rubocop.yml
Gemfile.lock
bin/gl-report
gatherlogs_reporter.gemspec
habitat-packages/cli/plan.sh

Because of the way the cli scripts were revamped the habitat packages
were no longer being build correctly to replace the shebang

Fix building the hab pkg

---

Gemfile.lock
bin/gl-version

This was causing the hab package installations to break because it
doesn't have the correct environment for the gemfile

Remove bundler setup require

---

.expeditor/config.yml
CHANGELOG.md

Seeing if we can get the changelog setup to have the rollup changes happen similar to chef and chef-dk
Since this involves expeditor changes add them for a request to review as well.

Add changelog rollup expeditor configs

---

spec/gatherlogs/version_spec.rb

This isn't really testing anything meaningful and breaks every time we
want to update the version of inspec we use

Remove test that depends on specific version of dep
